-- MySQL Script generated by MySQL Workbench
-- 06/27/15 18:29:52
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`accounts` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `Nickname` VARCHAR(45) NOT NULL COMMENT '',
  `LastName` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `FirstName` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `Gender` ENUM('Male','Female') NULL DEFAULT NULL COMMENT '',
  `Password` VARCHAR(60) NOT NULL COMMENT '',
  `BirthDate` DATE NULL DEFAULT NULL COMMENT '',
  `About` TEXT NULL DEFAULT NULL COMMENT '',
  `GameRating` INT(11) NOT NULL COMMENT '',
  `Mail` VARCHAR(30) NOT NULL COMMENT '',
  `Picture` VARCHAR(400) NOT NULL COMMENT '',
  PRIMARY KEY (`ID`)  COMMENT '',
  UNIQUE INDEX `Nickname_UNIQUE` (`Nickname` ASC)  COMMENT '')
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`conversations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`conversations` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `AccIDFrom` INT(11) NOT NULL COMMENT '',
  `AccIDTo` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`ID`)  COMMENT '',
  INDEX `fk_Conversations_Accounts1_idx` (`AccIDFrom` ASC)  COMMENT '',
  INDEX `fk_Conversations_Accounts2_idx` (`AccIDTo` ASC)  COMMENT '',
  CONSTRAINT `fk_Conversations_Accounts1`
  FOREIGN KEY (`AccIDFrom`)
  REFERENCES `mydb`.`accounts` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Conversations_Accounts2`
  FOREIGN KEY (`AccIDTo`)
  REFERENCES `mydb`.`accounts` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`friends`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`friends` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `AccIDFrom` INT(11) NOT NULL COMMENT '',
  `AccIDTo` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`ID`)  COMMENT '',
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC)  COMMENT '',
  INDEX `fk_Friends_Accounts_idx` (`AccIDFrom` ASC)  COMMENT '',
  INDEX `fk_Friends_Accounts1_idx` (`AccIDTo` ASC)  COMMENT '',
  CONSTRAINT `fk_Friends_Accounts`
  FOREIGN KEY (`AccIDFrom`)
  REFERENCES `mydb`.`accounts` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Friends_Accounts1`
  FOREIGN KEY (`AccIDTo`)
  REFERENCES `mydb`.`accounts` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`games` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `Date` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`ID`)  COMMENT '')
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`messages` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `Text` TEXT NULL DEFAULT NULL COMMENT '',
  `Sender` ENUM('1','2') NOT NULL COMMENT '',
  `Conversations_ID` INT(11) NOT NULL COMMENT '',
  `Date` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`ID`)  COMMENT '',
  INDEX `fk_Messages_Conversations1_idx` (`Conversations_ID` ASC)  COMMENT '',
  CONSTRAINT `fk_Messages_Conversations1`
  FOREIGN KEY (`Conversations_ID`)
  REFERENCES `mydb`.`conversations` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`participations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`participations` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `GameID` INT(11) NOT NULL COMMENT '',
  `AccID` INT(11) NOT NULL COMMENT '',
  `RatingChange` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`ID`)  COMMENT '',
  INDEX `fk_Participations_Games1_idx` (`GameID` ASC)  COMMENT '',
  INDEX `fk_Participations_Accounts1_idx` (`AccID` ASC)  COMMENT '',
  CONSTRAINT `fk_Participations_Accounts1`
  FOREIGN KEY (`AccID`)
  REFERENCES `mydb`.`accounts` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Participations_Games1`
  FOREIGN KEY (`GameID`)
  REFERENCES `mydb`.`games` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`waitingfriends`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`waitingfriends` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `AccIDFrom` INT(11) NOT NULL COMMENT '',
  `AccIDTo` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`ID`)  COMMENT '',
  INDEX `fk_WaitingFriends_Accounts1_idx` (`AccIDFrom` ASC)  COMMENT '',
  INDEX `fk_WaitingFriends_Accounts2_idx` (`AccIDTo` ASC)  COMMENT '',
  CONSTRAINT `fk_WaitingFriends_Accounts1`
  FOREIGN KEY (`AccIDFrom`)
  REFERENCES `mydb`.`accounts` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_WaitingFriends_Accounts2`
  FOREIGN KEY (`AccIDTo`)
  REFERENCES `mydb`.`accounts` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`UnreadMessages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UnreadMessages` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `ReceiverID` INT(11) NOT NULL COMMENT '',
  `SenderNickname` VARCHAR(45) NOT NULL COMMENT '',
  `Text` TEXT NOT NULL COMMENT '',
  `Date` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`ID`)  COMMENT '',
  INDEX `fk_UnreadMessages_accounts1_idx` (`ReceiverID` ASC)  COMMENT '',
  CONSTRAINT `fk_UnreadMessages_accounts1`
  FOREIGN KEY (`ReceiverID`)
  REFERENCES `mydb`.`accounts` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;